name: Deploy QA

on:
  push:
    branches:
      - QA  # Solo se ejecuta en la rama QA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Clonar el repositorio
        uses: actions/checkout@v4

      - name: ğŸ”‘ Iniciar sesiÃ³n en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ—ï¸ Construir la imagen Docker
        run: |
          # Construir la imagen Docker desde la carpeta raÃ­z donde estÃ¡ el Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sistema_bancario:qa -f Dockerfile .

      - name: ğŸš€ Subir imagen a Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sistema_bancario:qa
